
service: nbc-project-brian-carlson

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  stage: dev
  environment:
    variable2: "https://api.coinranking.com/v1/public/coin/1/history/30d"

# you can add packaging information here
#package:
#  patterns:
#    - '!exclude-me.py'
#    - '!exclude-me-dir/**'
#    - include-me.py
#    - include-me-dir/**

plugins:
  - serverless-offline

functions:
  schema1:
    handler: handler.schema1_handler
    events:
      - httpApi:
          path: /schema1
          method: get
  schema2:
    handler: handler.schema2_handler
    events:
      - httpApi:
          path: /schema2
          method: get
